//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weathersun8889.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 會員
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 會員()
        {
            this.系統回報資料 = new HashSet<系統回報資料>();
            this.身分驗證資料 = new HashSet<身分驗證資料>();
            this.穿搭資料 = new HashSet<穿搭資料>();
            this.虛擬人像 = new HashSet<虛擬人像>();
            this.管理員 = new HashSet<管理員>();
        }
    
        public string 會員帳號 { get; set; }
        public string 性別 { get; set; }
        public string 用戶名 { get; set; }
        public byte[] 個人頭貼 { get; set; }
        public string 會員密碼 { get; set; }
        public Nullable<System.DateTime> 生日 { get; set; }
        public string 居住地區 { get; set; }
    
        public virtual 公告事項 公告事項 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<系統回報資料> 系統回報資料 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<身分驗證資料> 身分驗證資料 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<穿搭資料> 穿搭資料 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<虛擬人像> 虛擬人像 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<管理員> 管理員 { get; set; }
    }
}
