//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weathersun8889.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 商品
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 商品()
        {
            this.商品推薦表 = new HashSet<商品推薦表>();
        }
    
        public int 商品標籤 { get; set; }
        public decimal 商品售價 { get; set; }
        public string 商品名稱 { get; set; }
        public string 商品類別 { get; set; }
        public byte[] 商品圖片 { get; set; }
        public string 廠商名稱 { get; set; }
        public string 商品連結 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<商品推薦表> 商品推薦表 { get; set; }
    }
}
