//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weathersun8889.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseWSEntities5 : DbContext
    {
        public DatabaseWSEntities5()
            : base("name=DatabaseWSEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<商品> 商品 { get; set; }
        public virtual DbSet<貼文> 貼文 { get; set; }
        public virtual DbSet<會員> 會員 { get; set; }
        public virtual DbSet<Hashtag> Hashtag { get; set; }
        public virtual DbSet<公告事項> 公告事項 { get; set; }
        public virtual DbSet<系統回報資料> 系統回報資料 { get; set; }
        public virtual DbSet<身分驗證資料> 身分驗證資料 { get; set; }
        public virtual DbSet<穿搭資料> 穿搭資料 { get; set; }
        public virtual DbSet<商品推薦表> 商品推薦表 { get; set; }
        public virtual DbSet<虛擬人像> 虛擬人像 { get; set; }
        public virtual DbSet<管理員> 管理員 { get; set; }
    }
}
