//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weathersun8889
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProId { get; set; }
        public decimal ProPrice { get; set; }
        public string ProName { get; set; }
        public string ProCategory { get; set; }
        public string ProShopName { get; set; }
        public string ProUrl { get; set; }
        public string ProItemNo { get; set; }
        public string ProPic { get; set; }
    }
}
